import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main></main>
  </>;
}

{
  /* <button
  onClick={async () => {
    const 결과 = await axios.get("http://localhost:3000/api");
    console.log(결과);
  }}
>
  api 요청해보기
</button> */
}
